baseURL: https://www.providencehealthtech.com/
languageCode: en-us
title: Providence Healthtech
menu:
  main:
    # - name: Home
    #   url: /
    #   weight: 1
    - name: Our Services
      url: /services/
      weight: 1
    # - name: Who We Serve
    #   url: /who-we-serve/
    #   weight: 2
    # - name: Why Choose Providence
    #   url: /why-choose-providence
    #   weight: 3
    - name: Global Health Initiative
      weight: 2
      url: /services/global-health
    - name: About
      weight: 4
      url: /about/
    - name: Schedule a Demo
      weight: 5
      params:
        classes:
          - cta
          - ml-5
      url: 'schedule-a-demo'
  footer:
    - name: Home
      url: /
      weight: 1
    - name: Contact
      url: /contact
      weight: 2
    - name: Newsroom
      url: /newsroom
      weight: 3
permalinks:
  post: "/:year/:month/:day/:slug/"
  pages: "/:filename/"
params:
  homepage_meta_tags:
    meta_description: "Providence Healthtech is a Health IT firm specializing in cloud-based EMR solutions."
    meta_og_title: "Providence Healthtech"
    meta_og_type: "website"
    meta_og_url: "https://providencehealthtech.com"
    meta_og_image: "https://raw.githubusercontent.com/providencehealthtech/providencehealthtech.github.io/main/static/images/og_image.jpg"
    meta_og_description: "Providence Healthtech is a health IT firm specializing in cloud-based EMR solutions."
    meta_twitter_card: "summary"
  location: Winter Park, FL
  logo: img/logo.png
  logo_small: img/logo.png
  google_analytics_id: G-0PN8Q2WGNG
module:
  # replacements: "github.com/providencehealthtech/hugo-hero-theme -> ../../hugo-hero-theme"
  imports:
    - path: github.com/providencehealthtech/hugo-hero-theme